# Generated by Django 4.2.7 on 2023-11-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product_categories", old_name="Pid", new_name="Categorieid",
        ),
        migrations.RemoveField(model_name="product", name="id",),
        migrations.AlterField(
            model_name="product",
            name="Pid",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
